log_level = "warn"
position = "Top"
app_launcher_cmd = "walker"

[modules]
left = [ [ "AppLauncher", "Updates", "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [  "Tray", "Clock", "Privacy", "Settings" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'ghostty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "ghostty -e bluetuith"

[appearance]
style = "Solid"
text_color = "#D3C6AA"
workspace_colors = ["#A7C080","#83C092"]

[appearance.background_color]
base = "#272E33"
strong = "#1E2326"
weak = "#4F5B58"

[appearance.primary_color]
base = "#A7C080"

[appearance.danger_color]
base = "#E67E80"
weak = "#E69875"
