force_keyboard_focus = true
selection_wrap = true
theme = "Everforest"
hide_action_hints = true

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No Results" }

[keybinds]
quick_activate = []

[columns]
symbols = 1
